require('dotenv').config();
const mongoose = require('mongoose');
const Contractor = require('../src/models/Contractor');

function parseWorkTypes(raw) {
  if (!raw) return [];
  return raw.split(',').map(s => s.trim()).filter(Boolean);
}

function parseTurnover(raw) {
  if (!raw) return undefined;
  const s = raw.toString().replace(/[^0-9.]/g, '');
  const n = parseFloat(s);
  return isNaN(n) ? undefined : n;
}

function parseRefs(raw) {
  if (!raw || raw === 'No' || raw === 'NA') return [undefined, undefined];
  const parts = raw.split(',');
  return [parts[0]?.trim() || undefined, parts[1]?.trim() || undefined];
}

function cleanMobile(raw) {
  if (!raw) return '';
  return raw.toString().replace(/\s/g, '').replace(/^\+91/, '').slice(0, 15);
}

const VENDORS = [
  { vendorCode:'VC-0001', companyName:'Shri Banke Bihari Construction', ownerName:'Lokendra Singh', address:'House no. 838 Green south Avenue colony, shivpuri link road Gwalior', mobile:'9340792520', alternateMobile:'9926225939', email:'ls.gwalior38@gmail.com', accountHolderName:'Shri Banke Bihari Construction', bankName:'Punjab National Bank', accountNumber:'51615011000235', ifscCode:'PUNB0516110', branchName:'Gwalior Sada', gstNumber:'23BVAPS7585Q2ZN', panNumber:'', workTypes:'1. General contractors, 2. Excavation, 3. Concrete, 19. Masonry', references:'Larsen and Toubro limited construction, Government water resources department', averageTurnover:'4 crore' },
  { vendorCode:'VC-0002', companyName:'Ambika Construction', ownerName:'Chhaviram Mahor', address:'Dongerpur putlighar morar', mobile:'9589678059', alternateMobile:'', email:'', accountHolderName:'Ambika Construction', bankName:'State Bank of India', accountNumber:'35310755814', ifscCode:'SBIN0030258', branchName:'University Road Thatipur', gstNumber:'23ALKPM9789P1ZX', panNumber:'', workTypes:'1. General contractors, 3. Concrete, 5. Steel, 15. Plaster, 16. Flooring, 19. Masonry', references:'', averageTurnover:'' },
  { vendorCode:'VC-0003', companyName:'Ravi Kushwah', ownerName:'Ravi Kushwah', address:'Koteswar colony', mobile:'9399805536', alternateMobile:'', email:'kushwahravi59459@gmail.com', accountHolderName:'Ravi Kushwah', bankName:'Madhya Pradesh Gramin Bank', accountNumber:'203051030017535', ifscCode:'BKIDONAMRGB', branchName:'Sankarpur', gstNumber:'', panNumber:'CJQPK8065A', workTypes:'7. Electrical', references:'', averageTurnover:'' },
  { vendorCode:'VC-0004', companyName:'Shriram Associates', ownerName:'Dharmendra Kumar Jatav', address:'A2 Vasundhara Garden City Road, Near rational kids Academy, Aastha nagar, Adityapuram Gwalior', mobile:'9770107684', alternateMobile:'8319498722', email:'dharmendra7684@gmail.com', accountHolderName:'Shriram Associates', bankName:'HDFC Bank', accountNumber:'50200001195786', ifscCode:'HDFC0002744', branchName:'Baradari Chowk Jhansi', gstNumber:'23AJEPJ5581G2ZA', panNumber:'', workTypes:'10. Fire alarm and sprinkler', references:'Sharma Associates, D. B Mall', averageTurnover:'30' },
  { vendorCode:'VC-0005', companyName:'Nemichand Sagar', ownerName:'Nemichand Sagar', address:'Ramua Ward no. 61', mobile:'8717840596', alternateMobile:'8770080135', email:'nemisagar1987@gmail.com', accountHolderName:'', bankName:'Central Bank of India', accountNumber:'3090146623', ifscCode:'CBINO281952', branchName:'Mohanpur', gstNumber:'', panNumber:'', workTypes:'8. Plumbing', references:'', averageTurnover:'' },
  { vendorCode:'VC-0006', companyName:'Rajesh Plumber', ownerName:'Rajesh Kushwaha', address:'Jagnapura no1 gaasmandi gwalior', mobile:'7583064578', alternateMobile:'8839437621', email:'', accountHolderName:'Rajesh Kushwaha', bankName:'Bank of India', accountNumber:'945310110015739', ifscCode:'BKID0009453', branchName:'Foolbagh Sakha', gstNumber:'', panNumber:'', workTypes:'8. Plumbing', references:'Gardan City', averageTurnover:'' },
  { vendorCode:'VC-0007', companyName:'Ullash Jha', ownerName:'Ullash Jha', address:'Chandan nagar koteswar mandir', mobile:'7566501936', alternateMobile:'8446539453', email:'ullashjh6@gmail.com', accountHolderName:'Ullash Jha S/O Ashok Kumar Jha', bankName:'Punjab National Bank', accountNumber:'3237001500108312', ifscCode:'PUNB0190900', branchName:'Tansen Road', gstNumber:'', panNumber:'', workTypes:'3. Concrete', references:'', averageTurnover:'' },
  { vendorCode:'VC-0008', companyName:'Shyamsundar Road Work', ownerName:'Shyamsundar Maurya', address:'Utila gwalior', mobile:'9009522138', alternateMobile:'7049421839', email:'', accountHolderName:'Shyamsundar', bankName:'Nagrik Sahakari Bank', accountNumber:'470005023003466', ifscCode:'INDB0NSBG05', branchName:'City Centre Thatipur', gstNumber:'', panNumber:'', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0009', companyName:'Kiran Bhadauriya', ownerName:'Kiran Bhadauriya', address:'A38 Green South Avenue', mobile:'9340792520', alternateMobile:'', email:'', accountHolderName:'Kiran Bhadauriya', bankName:'Punjab National Bank', accountNumber:'5161100100001637', ifscCode:'PUNB0516110', branchName:'Gwalior Sada', gstNumber:'', panNumber:'', workTypes:'2. Excavation', references:'', averageTurnover:'' },
  { vendorCode:'VC-0010', companyName:'C.P. Solar Energy', ownerName:'Arjun Mandelia', address:'City center Site no-1 Gwalior', mobile:'9111419111', alternateMobile:'9111118586', email:'CP.SOLAR@OUTLOOK.COM', accountHolderName:'C.P. Solar Energy', bankName:'Bank of Baroda', accountNumber:'67940200002600', ifscCode:'BARBOVJCCGW', branchName:'City Centre', gstNumber:'23ALKPM0108Q1ZO', panNumber:'', workTypes:'Solar work', references:'', averageTurnover:'' },
  { vendorCode:'VC-0011', companyName:'Prakash Ceiling Work', ownerName:'Prakash Singh Sisodiya', address:'Gudi guda ka naka gwalior', mobile:'9826351414', alternateMobile:'9826351414', email:'', accountHolderName:'Prakash Singh Sisodiya', bankName:'Union Bank', accountNumber:'517002010008067', ifscCode:'UBIN0551708', branchName:'Miss Hill BR Gwalior', gstNumber:'', panNumber:'', workTypes:'Ceiling work', references:'', averageTurnover:'' },
  { vendorCode:'VC-0012', companyName:'Airsource Services', ownerName:'Rakesh Sonava / Ravi Bajpai', address:'G2 Vasudeva apartment, main bus stand Devli Road, New Delhi-110062', mobile:'9911889400', alternateMobile:'8949520035', email:'airsourceservices@gmail.com', accountHolderName:'Airsource Services', bankName:'Punjab National Bank', accountNumber:'05401100002410', ifscCode:'PSIB0000540', branchName:'New Delhi Okhla', gstNumber:'07AHJPS655N2ZE', panNumber:'', workTypes:'9. HVAC', references:'NA', averageTurnover:'350' },
  { vendorCode:'VC-0013', companyName:'Firoz Khan', ownerName:'Firoz Khan', address:'Chandrawadni', mobile:'9977053264', alternateMobile:'', email:'', accountHolderName:'', bankName:'', accountNumber:'', ifscCode:'', branchName:'', gstNumber:'', panNumber:'', workTypes:'18. Painting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0014', companyName:'Ekta Concrete Solution', ownerName:'Pancham', address:'Bhind road gwalior', mobile:'8889640764', alternateMobile:'', email:'ektaconcrete@gmail.com', accountHolderName:'Ekta Concrete Solution', bankName:'ICICI Bank', accountNumber:'099205500519', ifscCode:'ICIC0000992', branchName:'Murena', gstNumber:'', panNumber:'', workTypes:'3. Concrete, Core cutting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0015', companyName:'Paras Nath', ownerName:'Paras Nath', address:'Hurawali, Gwalior', mobile:'8238736201', alternateMobile:'', email:'', accountHolderName:'Paras Nath', bankName:'Punjab National Bank', accountNumber:'1301000100233648', ifscCode:'PUNB0130100', branchName:'Murena Banmore', gstNumber:'', panNumber:'', workTypes:'Fire fabricator', references:'', averageTurnover:'' },
  { vendorCode:'VC-0016', companyName:'Ravindra Kumar Kushwah', ownerName:'Ravindra Kumar Kushwah', address:'Ramta pura gwalior', mobile:'9329248142', alternateMobile:'', email:'', accountHolderName:'Ravindra Kumar Kushwah', bankName:'State Bank of India', accountNumber:'11901420056', ifscCode:'SBIN0004088', branchName:'Foolbagh Gwalior', gstNumber:'', panNumber:'', workTypes:'3. Concrete', references:'', averageTurnover:'' },
  { vendorCode:'VC-0017', companyName:'Tyagi Construction', ownerName:'Gyanendra Tyagi', address:'Maa pitambara computer institute goura complex near bhagwati garden chouhan pyau thatipur Gwalior 474011', mobile:'7509583663', alternateMobile:'', email:'tyaginkt95@gmail.com', accountHolderName:'Nitesh Tyagi', bankName:'Central Bank of India', accountNumber:'3681631213', ifscCode:'CBIN0281373', branchName:'Pachbigha Road', gstNumber:'', panNumber:'', workTypes:'Concrete solution and core cutting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0018', companyName:'Naval Giri Goswami', ownerName:'Naval Giri Goswami', address:'Tahsil vijaypur district sheopur village ladpura post eklod', mobile:'6263834991', alternateMobile:'', email:'', accountHolderName:'Naval Giri Goswami', bankName:'Punjab National Bank', accountNumber:'2764000100022990', ifscCode:'PUNB0274600', branchName:'Vijaypur', gstNumber:'', panNumber:'', workTypes:'16. Flooring', references:'', averageTurnover:'' },
  { vendorCode:'VC-0019', companyName:'Abdul Ahashad', ownerName:'Abdul Ahshad', address:'Awadpura indra nagar gwalior', mobile:'7999956598', alternateMobile:'', email:'', accountHolderName:'Abdul Ahshad', bankName:'State Bank of India', accountNumber:'63031161088', ifscCode:'SBIN0030137', branchName:'Kampoo', gstNumber:'', panNumber:'', workTypes:'Waterproof', references:'', averageTurnover:'' },
  { vendorCode:'VC-0020', companyName:'Yatendra Singh', ownerName:'Yatendra Singh', address:'Morar', mobile:'7999633025', alternateMobile:'', email:'', accountHolderName:'', bankName:'Axis Bank', accountNumber:'924010011401698', ifscCode:'UTIB0001678', branchName:'Murar', gstNumber:'', panNumber:'', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0021', companyName:'Kumar Developers', ownerName:'Satish Kumar', address:'Govindpuri', mobile:'7999633025', alternateMobile:'', email:'', accountHolderName:'Kumar Developers', bankName:'Axis Bank', accountNumber:'922020003374260', ifscCode:'UTIB0003981', branchName:'Achaleswar', gstNumber:'', panNumber:'', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0022', companyName:'Dharamjit', ownerName:'Dharamjit', address:'Hurawali murar pawansut colony', mobile:'9009921407', alternateMobile:'', email:'', accountHolderName:'Dharamjeet', bankName:'SBI', accountNumber:'53009444423', ifscCode:'SBIN0030096', branchName:'Baradari chouraha morar', gstNumber:'', panNumber:'AIJPD0896Q', workTypes:'15. Plaster, 19. Masonry', references:'', averageTurnover:'' },
  { vendorCode:'VC-0023', companyName:'Pooran Singh Kushwah', ownerName:'Pooran Singh Kushwah', address:'Govt. school Ramta pura gwalior', mobile:'9131921330', alternateMobile:'7049326956', email:'', accountHolderName:'Pooran Singh Kushwah', bankName:'Punjab National Bank', accountNumber:'0328000100460903', ifscCode:'PNUB0032800', branchName:'Mall road morar gwalior', gstNumber:'', panNumber:'HIYPS8800R', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0024', companyName:'Sanjay Goyal (Mashi Construction and Contractor)', ownerName:'Sanjay Goyal', address:'Laxmiganj ab road lashkar gwalior madhav nagar gate no. 1', mobile:'8817403372', alternateMobile:'', email:'gsanjqy@gmail.com', accountHolderName:'Mashi construction and contractor', bankName:'HDFC Bank', accountNumber:'50200088327145', ifscCode:'HDFC0000192', branchName:'City Centre', gstNumber:'', panNumber:'CMSPJ7148C', workTypes:'Structure and civil contractor', references:'', averageTurnover:'' },
  { vendorCode:'VC-0025', companyName:'Shubhankar Ceremics and Marbles', ownerName:'Aakash Kaushik', address:'58 Kanti Nagar Gwalior', mobile:'9346516507', alternateMobile:'8085042391', email:'SHUBHANKARCERAMICS@GMAIL.COM', accountHolderName:'Shubhankar Ceremics and Marbles', bankName:'HDFC Bank Ltd', accountNumber:'50200045326469', ifscCode:'HDFC0000192', branchName:'City Centre Gwalior', gstNumber:'23ARFPK8408A1Z9', panNumber:'ARFPK8408A', workTypes:'16. Flooring', references:'', averageTurnover:'' },
  { vendorCode:'VC-0026', companyName:'Girraj Prajapati', ownerName:'Girraj', address:'Kumarpura gwalior', mobile:'9754272057', alternateMobile:'', email:'', accountHolderName:'Girraj Prajapati', bankName:'Union Bank', accountNumber:'580802010001184', ifscCode:'UBIN0558087', branchName:'Union Bank', gstNumber:'', panNumber:'AVUPP6885D', workTypes:'Soil work', references:'', averageTurnover:'' },
  { vendorCode:'VC-0027', companyName:'Gaurav Bricks', ownerName:'Gaurav Jethwani', address:'Gram Tiletha, Sitholi Rail Spring Karkhane ke pass, Gwalior', mobile:'9820641045', alternateMobile:'', email:'', accountHolderName:'Gaurav Bricks', bankName:'HDFC Bank', accountNumber:'50200070557368', ifscCode:'HDFC0000192', branchName:'City Centre Gwalior', gstNumber:'23AYPPJ6441F1ZF', panNumber:'AYPPJ6441F', workTypes:'Brick Supplier', references:'', averageTurnover:'' },
  { vendorCode:'VC-0028', companyName:'Ganpat Soil Work', ownerName:'Ganpat Prajapati', address:'Kumarpura gwalior', mobile:'9575258153', alternateMobile:'', email:'', accountHolderName:'Ganpat Prajapati', bankName:'Union Bank', accountNumber:'580802010008288', ifscCode:'UBIN0558087', branchName:'Thatipur Primila Plaza', gstNumber:'', panNumber:'BIQPP68404', workTypes:'Soil work', references:'', averageTurnover:'' },
  { vendorCode:'VC-0029', companyName:'Prashant Singh', ownerName:'Prashant Singh', address:'Village takpura tehsil mehgaon adhokar mehgaon bhind', mobile:'8518070023', alternateMobile:'', email:'', accountHolderName:'Prashant Singh', bankName:'Central Bank of India', accountNumber:'5268540933', ifscCode:'CBIN0282036', branchName:'Amayan', gstNumber:'', panNumber:'AMXPC6688B', workTypes:'18. Painting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0030', companyName:'New Yadav Crane', ownerName:'Suman Yadav', address:'', mobile:'9993544491', alternateMobile:'9907765082', email:'arjunkushwah3881@gmail.com', accountHolderName:'Suman Yadav', bankName:'HDFC Bank', accountNumber:'50200050558980', ifscCode:'HDFC0003661', branchName:'HDFC Bank Dal bazar tiraha lashkar gwalior', gstNumber:'', panNumber:'AMKPY5126B', workTypes:'Crane service', references:'', averageTurnover:'' },
  { vendorCode:'VC-0031', companyName:"Siddiqui and Son's", ownerName:'Halimuddin Siddiqui', address:'Guda gudi ka naka gwalior', mobile:'9425109077', alternateMobile:'', email:'', accountHolderName:'Halimuddin Siddiqui', bankName:'Punjab National Bank', accountNumber:'0290008700006231', ifscCode:'PUNB0029000', branchName:'Naya Bazar', gstNumber:'', panNumber:'ARMPS8535K', workTypes:'Taxchure', references:'', averageTurnover:'' },
  { vendorCode:'VC-0032', companyName:'Maa Durga Construction', ownerName:'Sanjay Sahni', address:'City Centre', mobile:'9575741888', alternateMobile:'', email:'', accountHolderName:'Maa Durga Construction', bankName:'ICICI Bank', accountNumber:'656805600373', ifscCode:'ICICI0006568', branchName:'Anand Rathi Bldg', gstNumber:'', panNumber:'CYPPS4179F', workTypes:'15. Plaster', references:'', averageTurnover:'' },
  { vendorCode:'VC-0033', companyName:'Jai Bharat Industries', ownerName:'Savita Jethwani', address:'Gram Tiletha, Sitholi Rail Spring Karkhane ke pass, Gwalior', mobile:'9820641045', alternateMobile:'', email:'GAURAV.JETHWANI55@GMAIL.COM', accountHolderName:'Jai Bharat Industries', bankName:'HDFC Bank', accountNumber:'50200062332663', ifscCode:'HDFC0000192', branchName:'City Centre Gwalior', gstNumber:'23ABWPJ4345C1ZQ', panNumber:'ABWPJ4345C', workTypes:'Bricks Supplier', references:'', averageTurnover:'' },
  { vendorCode:'VC-0034', companyName:'Prabhat Industries', ownerName:'Renu Jethwani', address:'Gram Tiletha, Sitholi Rail Spring Karkhane ke pass, Gwalior', mobile:'9425307835', alternateMobile:'', email:'', accountHolderName:'Prabhat Industries', bankName:'HDFC Bank', accountNumber:'50200061730921', ifscCode:'HDFC0000192', branchName:'City Centre Gwalior', gstNumber:'23ABQPJ1948R1ZY', panNumber:'ABQPJ1948R', workTypes:'Bricks Supplier', references:'', averageTurnover:'' },
  { vendorCode:'VC-0035', companyName:'Chetan Pandey', ownerName:'Chetan Pandey', address:'Kampu gwalior', mobile:'7747082950', alternateMobile:'', email:'', accountHolderName:'Chetan Pandey', bankName:'Nagrik Sahakari Bank Maryadit Gwalior', accountNumber:'470005024012607', ifscCode:'INDB0NSB01', branchName:'City Centre', gstNumber:'', panNumber:'BTVPP9744F', workTypes:'Material', references:'', averageTurnover:'' },
  { vendorCode:'VC-0036', companyName:'Virendra Jatav', ownerName:'Virendra Jatav', address:'Sanjay nagar Kali Mata mandir gali no 2 ashok dr k pass lashkar gwalior', mobile:'7869443421', alternateMobile:'', email:'', accountHolderName:'Virendra Jatav', bankName:'State Bank of India', accountNumber:'20331126519', ifscCode:'SBIN0030417', branchName:'Laxmiganj mandi Shivam plaza gwalior', gstNumber:'', panNumber:'ARIPV8327L', workTypes:'3. Concrete', references:'', averageTurnover:'' },
  { vendorCode:'VC-0037', companyName:'Asphak Welding', ownerName:'Asphak', address:'Chutta ki bajariya', mobile:'9009071208', alternateMobile:'', email:'', accountHolderName:'Asphak', bankName:'SBI', accountNumber:'10554506759', ifscCode:'SBIN0000377', branchName:'Jiwaji Chowk', gstNumber:'', panNumber:'EQLPA0445N', workTypes:'13. Drywall, Fabrication', references:'', averageTurnover:'' },
  { vendorCode:'VC-0038', companyName:'Mukhtar Khan', ownerName:'Mukhtar Khan', address:'Gali no. 1, shitla basti, lashkar, apaganj, Gwalior', mobile:'7724022673', alternateMobile:'', email:'', accountHolderName:'Mukhtar Khan', bankName:'Central Bank of India', accountNumber:'3310034516', ifscCode:'CBIN0281682', branchName:'Mohan niwas kampoo road, gwalior', gstNumber:'', panNumber:'HZHPK2096H', workTypes:'18. Painting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0039', companyName:'Brijesh Babu', ownerName:'Brijesh Babu Dohare', address:'Siddharth Nagar', mobile:'9754688005', alternateMobile:'', email:'', accountHolderName:'Brijesh Babu Dohare', bankName:'SBI', accountNumber:'31863405824', ifscCode:'SBIN0004352', branchName:'City Centre', gstNumber:'', panNumber:'BYSPD4140F', workTypes:'Termite treatment', references:'', averageTurnover:'' },
  { vendorCode:'VC-0040', companyName:'Beer Singh', ownerName:'Beer Singh', address:'Kirar colony gali no. 1, kampoo, Lashkar, gwalior', mobile:'9165939427', alternateMobile:'', email:'', accountHolderName:'Beer Singh', bankName:'Punjab National Bank', accountNumber:'3237000100582234', ifscCode:'PUNB0323700', branchName:'Jayendra ganj, lashkar', gstNumber:'', panNumber:'DFHPS8728J', workTypes:'16. Flooring', references:'', averageTurnover:'' },
  { vendorCode:'VC-0041', companyName:'Deni Singh', ownerName:'Deni Singh', address:'Thakur mohalla gwalior', mobile:'8225817762', alternateMobile:'', email:'', accountHolderName:'Deni Singh', bankName:'Bank of Baroda', accountNumber:'39280100006089', ifscCode:'BARB0TALANA', branchName:'Tala nagari', gstNumber:'', panNumber:'GRLPS6585L', workTypes:'18. Painting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0042', companyName:'Mukesh Singh', ownerName:'Mukesh Singh', address:'Gole ka mandir gwalior', mobile:'8103735026', alternateMobile:'', email:'', accountHolderName:'Mukesh Singh', bankName:'Indian Bank', accountNumber:'7195879520', ifscCode:'IDIB000B827', branchName:'BIMR', gstNumber:'', panNumber:'EVLPS6563Q', workTypes:'8. Plumbing', references:'', averageTurnover:'' },
  { vendorCode:'VC-0043', companyName:'Hiralal Kushwah', ownerName:'Hiralal Kushwah', address:'C-45 Tansen Nagar', mobile:'9770630391', alternateMobile:'', email:'', accountHolderName:'Hiralal Kushwah', bankName:'Punjab National Bank', accountNumber:'1909000100591179', ifscCode:'PUNB0190900', branchName:'Hazira Tansen Road, 477001', gstNumber:'', panNumber:'AJWPL5316K', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0044', companyName:'Naaz Furnitures', ownerName:'Nazim Ali', address:'Indranagar kampoo lashkar gwalior', mobile:'9752505568', alternateMobile:'8463842503', email:'nazimali635@gmail.com', accountHolderName:'Nazim Ali', bankName:'Kotak Mahindra Bank', accountNumber:'2012297607', ifscCode:'KKBK0005927', branchName:'Thatipur gwalior', gstNumber:'', panNumber:'BMJPA8885R', workTypes:'1. General contractors, 6. Window and door, 17. Finish carpentry', references:'', averageTurnover:'' },
  { vendorCode:'VC-0045', companyName:'Shri Girraj Fire Solutions', ownerName:'Jitendra Kumar', address:'Old Aampura Morena', mobile:'9424610757', alternateMobile:'9599625524', email:'jitendralala1991@gmail.com', accountHolderName:'Jitendra Kumar', bankName:'Uco Bank', accountNumber:'0043011057056', ifscCode:'UCBA0000043', branchName:'Morena', gstNumber:'', panNumber:'CXYPK7560A', workTypes:'10. Fire alarm and sprinkler', references:'UTS Safety System pvt. Ltd.', averageTurnover:'8.5' },
  { vendorCode:'VC-0046', companyName:'Sankalp Verma', ownerName:'Brijesh Verma', address:'Balaji dham', mobile:'9425112839', alternateMobile:'', email:'', accountHolderName:'Sankalp Verma', bankName:'SBI', accountNumber:'00000034946566092', ifscCode:'SBIN0030502', branchName:'Patel Nagar', gstNumber:'', panNumber:'', workTypes:'7. Electrical', references:'', averageTurnover:'' },
  { vendorCode:'VC-0047', companyName:'Shri Girraj Fire Solutions', ownerName:'Jitendra Kumar', address:'Old Aampura Morena', mobile:'9424610757', alternateMobile:'9599625524', email:'jitendralala1991@gmail.com', accountHolderName:'Jitendra Kumar', bankName:'Uco Bank', accountNumber:'00430110057056', ifscCode:'UCBA0000043', branchName:'Morena', gstNumber:'', panNumber:'CXYPK7560A', workTypes:'10. Fire alarm and sprinkler', references:'UTS Safety System pvt. Ltd.', averageTurnover:'7.5' },
  { vendorCode:'VC-0048', companyName:'MK Construction', ownerName:'Mukesh Kumar Kushwah', address:'201, 2nd floor Laxmi appartment dal bazar gwalior', mobile:'7415707173', alternateMobile:'', email:'', accountHolderName:'Mukesh Kumar Kushwah', bankName:'State Bank of India', accountNumber:'30379374245', ifscCode:'SBIN0004088', branchName:'PBB Phoolbaag Chauraha', gstNumber:'', panNumber:'AWEPK9575C', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0049', companyName:'Hindustan Nursery', ownerName:'Bablu Kushwah', address:'11/122 chini ka roza, ram bagh, kuberpur, yamuna bridge, agra up 282006', mobile:'8218087485', alternateMobile:'', email:'', accountHolderName:'Bablu Kushwah', bankName:'Jana Small Finance Bank', accountNumber:'4605020001102931', ifscCode:'JSFB0004605', branchName:'Sanjay place agra', gstNumber:'', panNumber:'DOKPK0027Q', workTypes:'20. Landscaping', references:'', averageTurnover:'' },
  { vendorCode:'VC-0050', companyName:'Akash Jatav', ownerName:'Akash Jatav', address:'Vard no. 4 Renhat', mobile:'7678307008', alternateMobile:'9617461986', email:'', accountHolderName:'Akash Jatav', bankName:'Union Bank', accountNumber:'583102120002116', ifscCode:'UBIN0558311', branchName:'Lashkar Gwalior', gstNumber:'', panNumber:'BURPJ4812K', workTypes:'Road cobel', references:'', averageTurnover:'' },
  { vendorCode:'VC-0051', companyName:'Om Sai Consultants', ownerName:'Sushil Kumar Shrivastava', address:'Peepal Chauraha near dandraua dham mandir D D Nagar Gwalior', mobile:'8889172768', alternateMobile:'8770385100', email:'sushil.ketan@gmail.com', accountHolderName:'Sushil Kumar Shrivastava', bankName:'State Bank of India Malanpur Bhind', accountNumber:'10702247017', ifscCode:'SBIN0009764', branchName:'Malanpur Bhind (M P)', gstNumber:'', panNumber:'BWEPS6766G', workTypes:'7. Electrical', references:'', averageTurnover:'' },
  { vendorCode:'VC-0052', companyName:'Vipin Goyal', ownerName:'Vipin Goyal', address:'Seva nagar, gwalior', mobile:'9926547506', alternateMobile:'', email:'', accountHolderName:'Vipin Goyal', bankName:'PNB', accountNumber:'0291000100204216', ifscCode:'PUNB0029100', branchName:'Sarafa Bazar', gstNumber:'', panNumber:'', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0053', companyName:'Shri Balaji Enterprises', ownerName:'Pawan Nahar', address:'Shide ki chawni', mobile:'9425115870', alternateMobile:'', email:'', accountHolderName:'Shri Balaji Enterprises', bankName:'Central Bank', accountNumber:'1357386637', ifscCode:'CBIN0280785', branchName:'Jayendra Ganj', gstNumber:'', panNumber:'', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0054', companyName:'Motiram Mahore', ownerName:'Motiram Mahore', address:'Dongarpur', mobile:'9589678059', alternateMobile:'', email:'', accountHolderName:'Motiram Mahore', bankName:'Bank of India', accountNumber:'945810110001329', ifscCode:'BKID0009458', branchName:'City Centre', gstNumber:'', panNumber:'AMTPR0835M', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0055', companyName:'Ashok Singh Kushwah', ownerName:'Ashok Singh Kushwah', address:'Dongarpur', mobile:'9589678059', alternateMobile:'', email:'', accountHolderName:'Ashok Singh Kushwah', bankName:'SBI', accountNumber:'63007378363', ifscCode:'SBIN0030258', branchName:'Alapur Gwalior', gstNumber:'', panNumber:'', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0056', companyName:'Yogendra Pop', ownerName:'Yogendra Singh', address:'Gospura no 1 hajeera gwalior', mobile:'8889179991', alternateMobile:'', email:'', accountHolderName:'Yogendra Singh Sisodiya', bankName:'Union Bank', accountNumber:'517002010029845', ifscCode:'UBIN0551708', branchName:'Miss High School Gwalior', gstNumber:'', panNumber:'DZRPS3595H', workTypes:'Pop paning', references:'', averageTurnover:'' },
  { vendorCode:'VC-0057', companyName:'G.A. Construction', ownerName:'Ullash Jha', address:'Chandra nagar koteshwar mandir', mobile:'7566501936', alternateMobile:'8446539453', email:'ullashjh6@gmail.com', accountHolderName:'Ullash Jha', bankName:'Punjab National Bank', accountNumber:'3237001500108312', ifscCode:'PUNB0190900', branchName:'Tansen Nagar', gstNumber:'', panNumber:'BFWPJ2340L', workTypes:'3. Concrete', references:'', averageTurnover:'' },
  { vendorCode:'VC-0058', companyName:'Sai Home Decor', ownerName:'Mahesh Chandwani', address:'Shop no.3 sangam plaza near sheetla Mata mandir lala ka bazar lashkar gwalior', mobile:'9826344766', alternateMobile:'', email:'mchandwani79@gmail.com', accountHolderName:'Sai Home Decor', bankName:'Nagrik Sahkari Bank Maryadit Gwalior', accountNumber:'470003021000534', ifscCode:'INDB0NSBG01', branchName:'Lala ka bazar lashkar gwalior', gstNumber:'Non', panNumber:'AIPPC1384G', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0059', companyName:'Amit Gupta', ownerName:'Vipin Goyal', address:'Meina wali gali, near old high court', mobile:'9926547506', alternateMobile:'9826264365', email:'Vipingoyal@gmail.com', accountHolderName:'Amit Gupta', bankName:'ICICI', accountNumber:'019701011182', ifscCode:'ICIC0000197', branchName:'City Center', gstNumber:'', panNumber:'BQJPG3532K', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0060', companyName:'Galav Aluminium', ownerName:'Rohit Agarwal', address:'34/1505 phalaka bazar lashkar gwalior 474001', mobile:'9926214077', alternateMobile:'', email:'agarwal17rohit@gmail.com', accountHolderName:'Galav Aluminium', bankName:'HDFC Bank', accountNumber:'50200042205568', ifscCode:'HDFC0001468', branchName:'JK Plaza gast ka tazia lashkar', gstNumber:'', panNumber:'AJMPA1234H', workTypes:'1. General contractors, 4. Framing, 6. Window and door, Aluminium work', references:'', averageTurnover:'' },
  { vendorCode:'VC-0061', companyName:'Mohan Sharma Choti', ownerName:'Mohan Sharma Choti', address:'Gali no 5 chandrwadni naka', mobile:'6263382901', alternateMobile:'', email:'', accountHolderName:'Mohan Sharma Choti', bankName:'Canara Bank', accountNumber:'77802010067520', ifscCode:'CNRB0017780', branchName:'Jayendraganj', gstNumber:'', panNumber:'BPBPC3121F', workTypes:'Cutting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0062', companyName:'Yogendra Singh Bhadoria', ownerName:'Yogendra Singh Bhadoria', address:'52, charai shyampur, rehnat, Gwalior', mobile:'9340792520', alternateMobile:'9926225939', email:'ls.gwalior38@gmail.com', accountHolderName:'Yogendra Singh Bhadoria', bankName:'Bank of India', accountNumber:'945810510000802', ifscCode:'BKID0009458', branchName:'Gwalior, City Centre', gstNumber:'', panNumber:'FHOPB8901F', workTypes:'2. Excavation', references:'', averageTurnover:'' },
  { vendorCode:'VC-0063', companyName:'NS Construction and Contractor', ownerName:'Sanjay', address:'Madhav nagar gate no.1, laxmiganj', mobile:'8817403372', alternateMobile:'', email:'', accountHolderName:'NS Construction and Contractor', bankName:'HDFC Bank', accountNumber:'59208800005555', ifscCode:'HDFC0000192', branchName:'City Centre', gstNumber:'', panNumber:'DRJPS4803N', workTypes:'3. Concrete', references:'', averageTurnover:'' },
  { vendorCode:'VC-0064', companyName:'Mohar Singh', ownerName:'Mohar Singh', address:'Morar', mobile:'9009719298', alternateMobile:'', email:'', accountHolderName:'Mohar Singh', bankName:'BOI', accountNumber:'945410110011362', ifscCode:'BKID0009454', branchName:'BOI', gstNumber:'', panNumber:'', workTypes:'Grinding on RCC', references:'', averageTurnover:'' },
  { vendorCode:'VC-0065', companyName:'Decore Line', ownerName:'Alim Siddiqui', address:'Gwalior', mobile:'9425115899', alternateMobile:'', email:'', accountHolderName:'Alim Suddiqui', bankName:'PNB', accountNumber:'3237002100021586', ifscCode:'PUNB0323700', branchName:'Jayendra Ganj', gstNumber:'', panNumber:'AOZPS1942L', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0066', companyName:'Balkrishna Ojha', ownerName:'Balkrishna Ojha', address:'Gwalior', mobile:'9826172356', alternateMobile:'', email:'', accountHolderName:'Balkrishna Ojha', bankName:'Nagrik Sahakari Bank', accountNumber:'470005023001965', ifscCode:'INDB0NSBG05', branchName:'Thatipur', gstNumber:'', panNumber:'', workTypes:'18. Painting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0067', companyName:'Narendra Singh Uchchadiya', ownerName:'Narendra Singh', address:'Shri nagar colony, morar', mobile:'8871361811', alternateMobile:'', email:'', accountHolderName:'Narendra Singh Uchchadiya', bankName:'Punjab National Bank', accountNumber:'6550001500000527', ifscCode:'PUNB0655000', branchName:'Thatipur Gwalior', gstNumber:'', panNumber:'ADBPU7877P', workTypes:'1. General contractors, 17. Finish carpentry, 18. Painting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0068', companyName:'Sunil Goyal', ownerName:'Sunil Goyal', address:'Murar bada gao gwalior', mobile:'9131485752', alternateMobile:'', email:'', accountHolderName:'Sunil Goyal', bankName:'HDFC Bank', accountNumber:'50100455658574', ifscCode:'HDFC0002744', branchName:'Baradari Branch', gstNumber:'', panNumber:'DLJPG2296H', workTypes:'18. Painting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0069', companyName:'Ahsan Khan', ownerName:'Ahsan Khan', address:'Kampoo, Gwalior', mobile:'9981710611', alternateMobile:'', email:'', accountHolderName:'Ahsan Khan', bankName:'Punjab National Bank', accountNumber:'0290000100339542', ifscCode:'PUNB0029000', branchName:'Lashkar Naya Bazar, Gwalior', gstNumber:'', panNumber:'', workTypes:'Pump Repairing', references:'', averageTurnover:'' },
  { vendorCode:'VC-0070', companyName:'Sanjay Kushwah', ownerName:'Sanjay Kushwah', address:'Jagna pura n 1 mevati mohalla gird gwalior', mobile:'7509788152', alternateMobile:'', email:'sanjaykushwah94@gmail.com', accountHolderName:'Sanjay Kushwah', bankName:'ICICI', accountNumber:'019701009501', ifscCode:'ICIC0000197', branchName:'City Center', gstNumber:'', panNumber:'BCBPK5265P', workTypes:'8. Plumbing', references:'', averageTurnover:'' },
  { vendorCode:'VC-0071', companyName:'Kavita Kushwah', ownerName:'Kavita Kushwah', address:'Ward no.6 mewati mohalla jagnapura no.1 gwalior', mobile:'7583064578', alternateMobile:'', email:'', accountHolderName:'Kavita Kushwah', bankName:'State Bank of India', accountNumber:'36960119097', ifscCode:'SBIN0016593', branchName:'Bahoddapur tiraha sagartal', gstNumber:'', panNumber:'FEVPK7796R', workTypes:'8. Plumbing', references:'', averageTurnover:'' },
  { vendorCode:'VC-0072', companyName:'Arvind Puri', ownerName:'Arvind Puri', address:'Gram charai, shyampur', mobile:'8959664775', alternateMobile:'', email:'', accountHolderName:'Arvind Puri', bankName:'SBI', accountNumber:'40243423089', ifscCode:'SBIN0061125', branchName:'Mohana', gstNumber:'', panNumber:'GAWPP2525R', workTypes:'Tile', references:'', averageTurnover:'' },
  { vendorCode:'VC-0073', companyName:'Ranjeet Kumar Jatav', ownerName:'Ranjeet Kumar Jatav', address:'Gudi guda ka naka gwalior', mobile:'7691929408', alternateMobile:'', email:'', accountHolderName:'Ranjeet Kumar Jatav', bankName:'Punjab National Bank', accountNumber:'1909000100614151', ifscCode:'PUNB0190900', branchName:'PUNB0190900', gstNumber:'', panNumber:'ASTPJ6151G', workTypes:'4. Framing', references:'', averageTurnover:'' },
  { vendorCode:'VC-0074', companyName:'Seema Core Cut', ownerName:'Seema', address:'Badarpura joura morena', mobile:'8889640764', alternateMobile:'', email:'', accountHolderName:'Seema', bankName:'Canara Bank', accountNumber:'6677101000444', ifscCode:'CNRB0006677', branchName:'Joura', gstNumber:'', panNumber:'FGVPS6752R', workTypes:'3. Concrete, Core cutting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0075', companyName:'Mukesh Kansana', ownerName:'Mukesh Kansana', address:'Adarsh nagar pintu park, gird, gwalior 474006', mobile:'8435278399', alternateMobile:'', email:'', accountHolderName:'Mukesh Kansana', bankName:'ICICI', accountNumber:'143901506500', ifscCode:'ICIC0001439', branchName:'Morar Gwalior Branch', gstNumber:'', panNumber:'EUUPK3467F', workTypes:'2. Excavation, Soil filling', references:'', averageTurnover:'' },
  { vendorCode:'VC-0076', companyName:'Omprakash Jha', ownerName:'Omprakash Jha', address:'Village mou Gohad bhind', mobile:'9575424641', alternateMobile:'', email:'', accountHolderName:'Omprakash Jha', bankName:'Punjab National Bank', accountNumber:'0866000100173420', ifscCode:'PUNB0086600', branchName:'Seondha', gstNumber:'', panNumber:'BPIPJ5894R', workTypes:'Pop', references:'', averageTurnover:'' },
  { vendorCode:'VC-0077', companyName:'Mahesh Gurjar', ownerName:'Mahesh Gurjar', address:'Dongarpur', mobile:'6263339825', alternateMobile:'', email:'', accountHolderName:'Mahesh Gurjar', bankName:'IndusLand Bank', accountNumber:'100049831211', ifscCode:'INDB0000487', branchName:'Sirol Branch', gstNumber:'', panNumber:'', workTypes:'2. Excavation', references:'', averageTurnover:'' },
  { vendorCode:'VC-0078', companyName:'Parvej', ownerName:'Parvej', address:'Islam kalchhilla gajiyabad', mobile:'7983545298', alternateMobile:'', email:'', accountHolderName:'Parvej', bankName:'Indian Bank', accountNumber:'50139623277', ifscCode:'IDIB000K533', branchName:'Kalchhina', gstNumber:'', panNumber:'DGNPP4255C', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0079', companyName:'Manoj Agrawal', ownerName:'Manoj Agrawal', address:'R J Puram, gird, gwalior mp', mobile:'8109879805', alternateMobile:'', email:'', accountHolderName:'Manoj Agrawal S/O Daudayal Agarwal', bankName:'Punjab National Bank', accountNumber:'12692191007354', ifscCode:'PUNB0126910', branchName:'IHM, Gwalior', gstNumber:'', panNumber:'AXOPA3426F', workTypes:'5. Steel', references:'', averageTurnover:'' },
  { vendorCode:'VC-0080', companyName:'Parvej', ownerName:'Parvej', address:'Kal chhina Gajiyabad', mobile:'7983545298', alternateMobile:'', email:'', accountHolderName:'Parvej', bankName:'HDFC', accountNumber:'50100793776221', ifscCode:'HDFC0006596', branchName:'Bhojpur, Gajiyabad', gstNumber:'', panNumber:'DGNPP4255C', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0081', companyName:'Ambika Construction', ownerName:'Banwari Mahor', address:'Doungarpur', mobile:'9589678059', alternateMobile:'', email:'', accountHolderName:'Bhupendra Singh', bankName:'State Bank of India', accountNumber:'32087952112', ifscCode:'SBIN0003180', branchName:'Rambagh Colony', gstNumber:'', panNumber:'', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0082', companyName:'Rakesh Sikarwar', ownerName:'Rakesh Sikarwar', address:'Sawarkar colony gudi guda ka naka gwalior', mobile:'7999633025', alternateMobile:'', email:'', accountHolderName:'Veerbhan Singh Jadon', bankName:'Axis Bank', accountNumber:'924010006559427', ifscCode:'UTIB0001678', branchName:'Murar', gstNumber:'', panNumber:'', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0083', companyName:'Jitendra Singh (Shri Banke Bihari Construction)', ownerName:'Jitendra Singh (Lokendra Singh)', address:'Bansi ka pura, ruar', mobile:'9340792520', alternateMobile:'7879748579', email:'', accountHolderName:'Jitendra Singh Tomar', bankName:'Punjab National Bank', accountNumber:'5161100100000861', ifscCode:'PUNB0516110', branchName:'Gwalior Sada', gstNumber:'', panNumber:'BWFPT7524N', workTypes:'2. Excavation', references:'', averageTurnover:'' },
  { vendorCode:'VC-0084', companyName:'Niket Jain', ownerName:'Niket Jain', address:'Swad restraunt ke pass murar', mobile:'7999633025', alternateMobile:'', email:'sagar@neotericgrp.in', accountHolderName:'Niket Jain', bankName:'HDFC', accountNumber:'50200042475701', ifscCode:'HDFC0002744', branchName:'Baradari, Murar', gstNumber:'', panNumber:'AUXPJ4364M', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0085', companyName:'Manish Kumar Jain', ownerName:'Manish Kumar Jain', address:'Ward no.11 vikash nagar bhind m.p', mobile:'7828246609', alternateMobile:'', email:'', accountHolderName:'Manish Kumar Jain', bankName:'Central Bank of India', accountNumber:'3499196162', ifscCode:'CBIN0280783', branchName:'Bhind', gstNumber:'', panNumber:'BGKPJ4052J', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0086', companyName:'Lokesh Singh', ownerName:'Lokesh Singh', address:'Morar', mobile:'8269526427', alternateMobile:'', email:'', accountHolderName:'Lokesh Singh', bankName:'Canara', accountNumber:'2897101015202', ifscCode:'CNRB0002897', branchName:'Unavailable', gstNumber:'', panNumber:'', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0087', companyName:'Niket Homes', ownerName:'Niket', address:'Chetak puri gwalior', mobile:'7999633025', alternateMobile:'', email:'', accountHolderName:'Niket Homes', bankName:'ICICI', accountNumber:'777705997900', ifscCode:'ICIC0006567', branchName:'Rajpayaga Road Branch', gstNumber:'', panNumber:'', workTypes:'3. Concrete', references:'', averageTurnover:'' },
  { vendorCode:'VC-0088', companyName:'Raheem Khan', ownerName:'Raheem Khan', address:'Gram kalyani post Takenpur teh Dabra puri Gwalior', mobile:'6261764502', alternateMobile:'', email:'', accountHolderName:'Raheem Khan', bankName:'SBI Kiosk Bank', accountNumber:'35509764006', ifscCode:'SBIN0006247', branchName:'Kalyani', gstNumber:'', panNumber:'KMMPK8330R', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0089', companyName:'Devendra Dhakar', ownerName:'Devendra Dhakar', address:'Nirara nai basti rithoniya, morena, Madhya Pradesh', mobile:'9753859389', alternateMobile:'', email:'', accountHolderName:'Devendra Dhakar', bankName:'Union Bank of India', accountNumber:'754202120023034', ifscCode:'UBIN0575429', branchName:'Sabalgarh', gstNumber:'', panNumber:'FYPPD1307B', workTypes:'16. Flooring', references:'', averageTurnover:'' },
  { vendorCode:'VC-0090', companyName:'Badam Singh', ownerName:'Badam Singh', address:'F5 Hanuman nagar, gird, Gwalior', mobile:'9826510175', alternateMobile:'', email:'', accountHolderName:'Badam Singh', bankName:'Central Bank of India', accountNumber:'1926011684', ifscCode:'CBIN0283006', branchName:'Malind malanpur industrial area branch bhind', gstNumber:'', panNumber:'ATHPS0322F', workTypes:'18. Painting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0091', companyName:'Vardaanya Windoors', ownerName:'Vaibhav Gupta', address:'E6/7 Harishankar Puram', mobile:'6262616181', alternateMobile:'', email:'vardaanya@gmail.com', accountHolderName:'Vardaanya Windoors', bankName:'HDFC Bank', accountNumber:'99999522265580', ifscCode:'HDFC0006307', branchName:'Achleswar Road', gstNumber:'', panNumber:'', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0092', companyName:'Ambika Glass and Hardware', ownerName:'Kshitiz Garg', address:'Dal bazar, guru walo ka bada, lashkar, gwalior', mobile:'7999413415', alternateMobile:'7987925863', email:'kshitizgarg60@gmail.com', accountHolderName:'Ambika Glass and Hardware', bankName:'Bank of India', accountNumber:'946320110000639', ifscCode:'BKID0009463', branchName:'Lohiya Bazar', gstNumber:'23DUSPG5476F1ZB', panNumber:'DUSPG5476F', workTypes:'Glass work', references:'', averageTurnover:'' },
  { vendorCode:'VC-0093', companyName:'Dulari Devi', ownerName:'Dulari Devi', address:'Ward 05 Madhopur chakdeoriya, dharphari', mobile:'7489594135', alternateMobile:'', email:'', accountHolderName:'Dulari Devi', bankName:'State Bank of India', accountNumber:'20392367712', ifscCode:'SBIN0016777', branchName:'Deoria', gstNumber:'', panNumber:'', workTypes:'16. Flooring, 19. Masonry', references:'', averageTurnover:'' },
  { vendorCode:'VC-0094', companyName:'Kamal Singh', ownerName:'Kamal Singh', address:'203 rehat dst gwalior', mobile:'9617461946', alternateMobile:'', email:'', accountHolderName:'Kamal Singh', bankName:'Canara Bank', accountNumber:'0295101029797', ifscCode:'CNRB0000295', branchName:'Canara Bank, Lashkar', gstNumber:'', panNumber:'JUZPS9217M', workTypes:'Paver and kerb stone work', references:'', averageTurnover:'' },
  { vendorCode:'VC-0095', companyName:'Shiva Pest Control India', ownerName:'Birjesh Babu Dohare', address:'1, Siddharth nagar mela ground, thatipur, Gwalior mp', mobile:'9754688005', alternateMobile:'', email:'birjesh.spc@gmail.com', accountHolderName:'Birjesh Babu Dohare', bankName:'SBI', accountNumber:'31863405824', ifscCode:'SBIN0004352', branchName:'City Center Gwalior', gstNumber:'', panNumber:'', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0096', companyName:'Neha Agarwal', ownerName:'Yogesh Agarwal', address:'Sikander kampoo', mobile:'9977023481', alternateMobile:'', email:'', accountHolderName:'Neha Agarwal', bankName:'Bank of India', accountNumber:'908410110007340', ifscCode:'BKID0009084', branchName:'Sinkander Kampoo', gstNumber:'', panNumber:'', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0097', companyName:'Gungun Enterprises', ownerName:'Balkrishna', address:'Ward no 23 adarsh colony', mobile:'9826172356', alternateMobile:'', email:'', accountHolderName:'Gungun Enterprises', bankName:'Nagarik Sahakari Bank', accountNumber:'470005021000563', ifscCode:'INDB0NSBG01', branchName:'City Centre', gstNumber:'', panNumber:'AARPO7525P', workTypes:'Pop', references:'', averageTurnover:'' },
  { vendorCode:'VC-0098', companyName:'Nikhil Prajapati', ownerName:'Nikhil Prajapati', address:'51/4 NH Ramoua morar', mobile:'8602058868', alternateMobile:'', email:'', accountHolderName:'Nikhil Prajapati', bankName:'SBI', accountNumber:'40736632367', ifscCode:'SBIN0016843', branchName:'New Collectorate Gwalior', gstNumber:'', panNumber:'HCAPP6400G', workTypes:'2. Excavation', references:'', averageTurnover:'' },
  { vendorCode:'VC-0099', companyName:'Rajni Verma', ownerName:'Rajni Verma', address:'D-3 Balaji Dham Enclave, Near Garden Homes, City Centre, Gwalior', mobile:'9425112839', alternateMobile:'', email:'rainbowlightgwl@gmail.com', accountHolderName:'Rajni Verma', bankName:'SBI', accountNumber:'30871563956', ifscCode:'SBIN0004352', branchName:'City Centre', gstNumber:'', panNumber:'AEOPV8853J', workTypes:'7. Electrical', references:'', averageTurnover:'' },
  { vendorCode:'VC-0100', companyName:'Krish Aluminium', ownerName:'Krish Aluminium', address:'Hanuman nagar, phalka bazar gwalior', mobile:'7415368934', alternateMobile:'', email:'', accountHolderName:'Krish Aluminium', bankName:'HDFC', accountNumber:'50200005601680', ifscCode:'HDFC0001468', branchName:'Gast Ka Tazia, Gwalior', gstNumber:'', panNumber:'ADLPG1219P', workTypes:'6. Window and door', references:'', averageTurnover:'' },
  { vendorCode:'VC-0101', companyName:'Raghavendra Sikarwar', ownerName:'Raghavendra Sikarwar', address:'Gwalior', mobile:'7509609569', alternateMobile:'', email:'', accountHolderName:'Raghvendra Singh', bankName:'PNB', accountNumber:'6388000000000000', ifscCode:'PUNB0655000', branchName:'Thatipur', gstNumber:'', panNumber:'', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0102', companyName:'Anchal Gupta', ownerName:'Anchal Gupta', address:'Gwalior', mobile:'9770248188', alternateMobile:'', email:'', accountHolderName:'Anchal Gupta', bankName:'Union Bank', accountNumber:'772602010002903', ifscCode:'UBIN0577260', branchName:'Dabra', gstNumber:'', panNumber:'BECPG0455C', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0103', companyName:'Akshara Garg', ownerName:'Kshitiz Garg', address:'Dal bazar', mobile:'7987925863', alternateMobile:'7999413415', email:'kshitizgarg60@gmail.com', accountHolderName:'Akshara Garg', bankName:'Bank of India', accountNumber:'946310110006597', ifscCode:'BKID0009463', branchName:'Naya Bazar', gstNumber:'', panNumber:'', workTypes:'Aluminium work', references:'', averageTurnover:'' },
  { vendorCode:'VC-0104', companyName:'Shivraj Dhakad', ownerName:'Shivraj Dhakad', address:'Ghati Gao', mobile:'9009946308', alternateMobile:'', email:'', accountHolderName:'Shivraj Dhakad', bankName:'Central Bank of India', accountNumber:'4042765304', ifscCode:'CBIN0282855', branchName:'Naugaon', gstNumber:'', panNumber:'GHJPD1550C', workTypes:'Soil Filling', references:'', averageTurnover:'' },
  { vendorCode:'VC-0105', companyName:'Mahesh Kushwah', ownerName:'Mahesh Kushwah', address:'Ghirvai', mobile:'9926237754', alternateMobile:'', email:'', accountHolderName:'Mahesh Kushwah', bankName:'IDBI Naya Bazar', accountNumber:'545104000004893', ifscCode:'IBKL0000545', branchName:'Naya Bazar', gstNumber:'', panNumber:'DOWPK7237E', workTypes:'3. Concrete', references:'', averageTurnover:'' },
  { vendorCode:'VC-0106', companyName:'Sachin Jatav', ownerName:'Sachin Jatav', address:'Ghoosipura gali number 8 murar, gwalior', mobile:'9516676966', alternateMobile:'', email:'', accountHolderName:'Sachin Jatav', bankName:'Union Bank of India', accountNumber:'580802010016366', ifscCode:'UBIN0558087', branchName:'Goshipura gali number 8 morar gwalior', gstNumber:'', panNumber:'BVAPJ0214K', workTypes:'18. Painting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0107', companyName:'Pathak Water Supplier', ownerName:'Rajendra Pathak', address:'Gwalior', mobile:'9907013465', alternateMobile:'', email:'', accountHolderName:'Pathak Water Supplyer', bankName:'Bank of Maharashtra', accountNumber:'60013339258', ifscCode:'MAHB0001183', branchName:'Gole Ka Mandir', gstNumber:'', panNumber:'', workTypes:'Boring', references:'', averageTurnover:'' },
  { vendorCode:'VC-0108', companyName:'Sourabh Kumar Singh', ownerName:'Sourabh Kumar Singh', address:'Gwalior', mobile:'9770107684', alternateMobile:'', email:'', accountHolderName:'Sourabh Kumar Singh', bankName:'Bank of India', accountNumber:'945410110010315', ifscCode:'BKID0009454', branchName:'St Paul Morar', gstNumber:'', panNumber:'', workTypes:'Fire', references:'', averageTurnover:'' },
  { vendorCode:'VC-0109', companyName:'Neeraj Kumar Goyal', ownerName:'Neeraj Kumar Goyal', address:'Purani jin gali no 1 morena', mobile:'9752113893', alternateMobile:'', email:'', accountHolderName:'Neeraj Kumar Goyal', bankName:'State Bank of India', accountNumber:'42797079935', ifscCode:'SBIN0016593', branchName:'Triloak chandr goyal purani jin gali no 1', gstNumber:'', panNumber:'ANIPG4086H', workTypes:'18. Painting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0110', companyName:'Rajveer Singh Jaat', ownerName:'Rajveer Singh Jaat', address:'Gram gadi, dabra', mobile:'6232472508', alternateMobile:'', email:'', accountHolderName:'Rajveer Singh Jaat', bankName:'IDBI Bank', accountNumber:'2238104000012324', ifscCode:'IBKL0002238', branchName:'Post sukhapatha gwalior', gstNumber:'', panNumber:'CEPPJ2110H', workTypes:'18. Painting', references:'', averageTurnover:'' },
  { vendorCode:'VC-0111', companyName:'Anguri Devi', ownerName:'Anguri Devi', address:'Mahendra Singh kushwah tekanpur Gwalior 475005', mobile:'7999332822', alternateMobile:'9340505488', email:'', accountHolderName:'Anguri Devi', bankName:'Central Bank of India', accountNumber:'5375186388', ifscCode:'CBIN0284688', branchName:'Tekanpur', gstNumber:'', panNumber:'CBWPD5443D', workTypes:'Soil supplier', references:'', averageTurnover:'' },
  { vendorCode:'VC-0112', companyName:'Ramesh Chandra Prajapati', ownerName:'Ramesh Chandra Prajapati', address:'Gwalior', mobile:'9826243502', alternateMobile:'', email:'', accountHolderName:'Ramesh Chandra Prajapati', bankName:'Central Bank of India', accountNumber:'3143795548', ifscCode:'CBIN0283461', branchName:'Ravi Nagar, Gwalior', gstNumber:'', panNumber:'AXLPP6066D', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0113', companyName:'Lambardar Earth Movers', ownerName:'Suraj Singh Kushwah', address:'Makoda word no. 4 Gwalior', mobile:'9691288980', alternateMobile:'8319004802', email:'', accountHolderName:'Suraj Singh Kushwah', bankName:'State Bank of India', accountNumber:'20360890480', ifscCode:'SBIN0030169', branchName:'Antri', gstNumber:'', panNumber:'DOXPK1752R', workTypes:'Soil', references:'', averageTurnover:'' },
  { vendorCode:'VC-0114', companyName:'Kundan Singh Ghamar', ownerName:'Kundan Singh Ghamar', address:'House no 13 lal tipara cantt. Area morar', mobile:'9229521289', alternateMobile:'9589678059', email:'', accountHolderName:'Kundan Singh Ghamar', bankName:'Punjab National Bank', accountNumber:'6550000100015924', ifscCode:'PUNB0655000', branchName:'Thatipur', gstNumber:'', panNumber:'AOFPG9786A', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0115', companyName:'Faizan Khan', ownerName:'Faizan Khan', address:'Ghosipura gwalior', mobile:'9301326624', alternateMobile:'7697003795', email:'', accountHolderName:'Faizan Khan', bankName:'HDFC Bank', accountNumber:'50100797026681', ifscCode:'HDFC0003707', branchName:'Bahodapur', gstNumber:'', panNumber:'KPCPK2507H', workTypes:'Fabrication Work', references:'', averageTurnover:'' },
  { vendorCode:'VC-0116', companyName:'Rahul Kain', ownerName:'Rahul Kain', address:'Guda bodh nagar, gwalior', mobile:'7691929408', alternateMobile:'', email:'', accountHolderName:'Rahul Kain', bankName:'Punjab National Bank', accountNumber:'1909000100617857', ifscCode:'PUNB0190900', branchName:'Kamal singh ka bagh sindh ki chawani gwalior', gstNumber:'', panNumber:'OACPK1796P', workTypes:'ACP work', references:'', averageTurnover:'' },
  { vendorCode:'VC-0117', companyName:'Well Home Decor Studio Pvt Ltd', ownerName:'Rajkumar Gupta', address:'Gwalior', mobile:'9111070001', alternateMobile:'', email:'', accountHolderName:'Well Home Decor Studio Private Limited', bankName:'ICICI Bank', accountNumber:'725305000011', ifscCode:'ICIC0007253', branchName:'D-5 Kailash Nagar, New Collectrate Road, Alkapuri, Gwalior', gstNumber:'23AAOCS5675A1ZB', panNumber:'', workTypes:'Aluminium', references:'', averageTurnover:'' },
  { vendorCode:'VC-0118', companyName:'Wellhome Decor Studio Pvt Ltd', ownerName:'Rajkumar Gupta', address:'Gwalior', mobile:'9111070001', alternateMobile:'9111070008', email:'wellhomedecorstudio@gmail.com', accountHolderName:'Wellhome Decor Studio', bankName:'ICICI', accountNumber:'725305000011', ifscCode:'ICIC0007253', branchName:'Alkapuri', gstNumber:'23AAOCS5675A1ZB', panNumber:'AAOCS5675A', workTypes:'6. Window and door, 16. Flooring', references:'', averageTurnover:'' },
  { vendorCode:'VC-0119', companyName:'Bhupendra Singh', ownerName:'Bhupendra Singh', address:'Dongarpur, gwalior', mobile:'7222955320', alternateMobile:'', email:'', accountHolderName:'Bhupendra Singh', bankName:'State Bank of India', accountNumber:'32087952112', ifscCode:'SBIN0003180', branchName:'Rambagh Colony, Gwalior', gstNumber:'', panNumber:'DORPS2668N', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0120', companyName:'Dinesh Mahor', ownerName:'Dinesh Mahor', address:'Gwalior', mobile:'', alternateMobile:'', email:'', accountHolderName:'Dinesh Mahor', bankName:'PNB', accountNumber:'6550001500002857', ifscCode:'PUNB0655000', branchName:'Gwalior', gstNumber:'', panNumber:'FPUM7284A', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0121', companyName:'Lotan Singh', ownerName:'Lotan Singh', address:'Girvai pahadi AB road ajaypur gwalior', mobile:'9826128744', alternateMobile:'', email:'', accountHolderName:'Lotan Singh', bankName:'Indian Overseas Bank', accountNumber:'318901000000436', ifscCode:'IOBA0003189', branchName:'Virpur', gstNumber:'', panNumber:'LHRPS8474H', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0122', companyName:'MS Tensile Structure', ownerName:'Shama Parveen', address:'Ghaziabad Uttar Pradesh', mobile:'7983545298', alternateMobile:'', email:'', accountHolderName:'Shama Parveen', bankName:'ICICI Bank', accountNumber:'125705500633', ifscCode:'ICIC0001257', branchName:'Modinagar Branch', gstNumber:'', panNumber:'IAZPP8634L', workTypes:'Tensile work', references:'', averageTurnover:'' },
  { vendorCode:'VC-0123', companyName:'Suraj Giri', ownerName:'Suraj Giri', address:'Ladpura sheopur', mobile:'7509502247', alternateMobile:'', email:'', accountHolderName:'Suraj Giri', bankName:'Bank of India', accountNumber:'905410110008745', ifscCode:'BKID0009054', branchName:'Shinde ki chawani', gstNumber:'', panNumber:'', workTypes:'Epoxy', references:'', averageTurnover:'' },
  { vendorCode:'VC-0124', companyName:'Maheshwari Electrical Contractor', ownerName:'Rajeev Maheshwari', address:'Vinay Nagar Sec 3 Gwalior', mobile:'7024701010', alternateMobile:'', email:'', accountHolderName:'Maheshwari Electrical Contractor', bankName:'HDFC Bank', accountNumber:'59230000001111', ifscCode:'HDFC0001468', branchName:'Gwalior', gstNumber:'23AAXFM5277E2ZV', panNumber:'', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0125', companyName:'Ambikeshwar', ownerName:'Ambikeshwar', address:'Gwalior', mobile:'9303648844', alternateMobile:'', email:'', accountHolderName:'Ambikeshwar', bankName:'Central Bank of India', accountNumber:'3875396471', ifscCode:'CBIN0284243', branchName:'Dewadand block khadgao', gstNumber:'', panNumber:'ESEPA0398M', workTypes:'Concrete plant operator', references:'', averageTurnover:'' },
  { vendorCode:'VC-0126', companyName:'Arjun Singh Mahor', ownerName:'Arjun Singh Mahor', address:'Pultighar, dongarpur, murar gwalior', mobile:'9826765882', alternateMobile:'', email:'', accountHolderName:'Arjun Singh', bankName:'SBI Bank', accountNumber:'63033766285', ifscCode:'SBIN0030502', branchName:'Patel Nagar Gwalior', gstNumber:'', panNumber:'BUZPS7951Q', workTypes:'16. Flooring', references:'', averageTurnover:'' },
  { vendorCode:'VC-0127', companyName:'Design Touch', ownerName:'Vikram Khatri / Aarusi Khatri', address:'Shantikunj Vasantkunj New Delhi-110070', mobile:'9811766887', alternateMobile:'8800742197', email:'STUDIOLINEC@GMAIL.COM', accountHolderName:'Aarushi Khatri', bankName:'State Bank of India', accountNumber:'43667785548', ifscCode:'SBIN0031668', branchName:'Vasantkunj New Delhi', gstNumber:'07EXPPK7824C1Z7', panNumber:'EXPPK7824C', workTypes:'Design Consultant', references:'Ishaan Group, Nirvana Resort', averageTurnover:'300' },
  { vendorCode:'VC-0128', companyName:'Fusion Furnish India Private Limited', ownerName:'Akhil Kadyan', address:'Plot no. 54, Udyog Kendra Ext-II, Ecotech III, Greater Noida 201306 Uttar Pradesh', mobile:'9718612266', alternateMobile:'9711263514', email:'akhil@fusionfurnish.com', accountHolderName:'Fusion Furnish India Pvt Ltd', bankName:'HDFC Bank', accountNumber:'50200074970180', ifscCode:'HDFC0000278', branchName:'Alpha Commercial Belt Greater Noida', gstNumber:'09AAFCF2426B1Z2', panNumber:'AAFCF2426B', workTypes:'Modular office Furniture', references:'DLF Limited, Signature Global India Limited', averageTurnover:'1800' },
  { vendorCode:'VC-0129', companyName:'Rajoriya Group Construction and Building Material Suppliers', ownerName:'Vivek Rajoriya', address:'277-278 cp colony morar gwalior', mobile:'9826126793', alternateMobile:'9425122625', email:'rajoriyavivek801@gmail.com', accountHolderName:'Rajoriya Group Construction and Building Material Suppliers', bankName:'HDFC Bank', accountNumber:'50200091646196', ifscCode:'HDFC0007840', branchName:'Gole Ka Mandir', gstNumber:'', panNumber:'AWUPR2800B', workTypes:'2. Excavation', references:'Goyal Housing, Radha Rani Construction', averageTurnover:'50' },
  { vendorCode:'VC-0130', companyName:'Star Stone Machinery', ownerName:'Ashu Vats', address:'75, Bhoapur Ator Road Ghaziabad (up) 201001', mobile:'9205959226', alternateMobile:'8800893014', email:'starstonem22@gmail.com', accountHolderName:'Ashu Vats', bankName:'Canara Bank', accountNumber:'86702010003056', ifscCode:'CNRB0018670', branchName:'Meerut Road, Modinagar', gstNumber:'', panNumber:'', workTypes:'Machinery', references:'', averageTurnover:'' },
  { vendorCode:'VC-0131', companyName:'RK Constructions', ownerName:'Sanjay Kushwah', address:'Sevanagar gwalior', mobile:'9329248143', alternateMobile:'', email:'', accountHolderName:'RK Constructions', bankName:'Axis Bank', accountNumber:'921020017428536', ifscCode:'UTIB0002974', branchName:'Near GDA Office Gwalior', gstNumber:'', panNumber:'ANFPK9515L', workTypes:'3. Concrete, 5. Steel', references:'', averageTurnover:'' },
  { vendorCode:'VC-0132', companyName:'Nand Kishor Mahor', ownerName:'Nand Kishor Mahor', address:'Gram dongarpur putli ghar ke pass morar gwalior', mobile:'8269211903', alternateMobile:'', email:'', accountHolderName:'Nandkishore Mahorre', bankName:'Bank of India', accountNumber:'945810110011951', ifscCode:'BKID0009458', branchName:'City Center', gstNumber:'', panNumber:'DHJPM0341H', workTypes:'1. General contractors', references:'', averageTurnover:'' },
  { vendorCode:'VC-0133', companyName:'Mangal', ownerName:'Mangal', address:'Bilaspur', mobile:'9399836429', alternateMobile:'', email:'', accountHolderName:'Mangal', bankName:'PNB', accountNumber:'6103001700401856', ifscCode:'PUNB0610300', branchName:'Pendra Branch', gstNumber:'', panNumber:'', workTypes:'', references:'', averageTurnover:'' },
  { vendorCode:'VC-0134', companyName:'Shivraj Dhakad', ownerName:'Shivraj Dhakad', address:'Mahatma Gandhi ke pass Lashkar girwai Naka ajaypur', mobile:'9009946308', alternateMobile:'', email:'', accountHolderName:'Shivraj Dhakad', bankName:'Central Bank of India', accountNumber:'4042765304', ifscCode:'CBIN0282855', branchName:'Naugaon', gstNumber:'', panNumber:'GHJPD1550C', workTypes:'2. Excavation', references:'', averageTurnover:'' },
  { vendorCode:'VC-0135', companyName:'MS Tensile', ownerName:'Shama Parveen', address:'Delhi', mobile:'7983545298', alternateMobile:'', email:'', accountHolderName:'MS Tensile Structure', bankName:'ICICI', accountNumber:'125705500633', ifscCode:'ICICI0001257', branchName:'Modinagar Branch', gstNumber:'', panNumber:'IAZPP8634L', workTypes:'Tensile', references:'', averageTurnover:'' },
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected to MongoDB\n');

  let updated = 0, created = 0;

  for (const v of VENDORS) {
    const [ref1, ref2] = parseRefs(v.references);
    const workTypes = parseWorkTypes(v.workTypes);
    const averageTurnover = parseTurnover(v.averageTurnover);
    const mobile = cleanMobile(v.mobile) || '0000000000';

    const payload = {
      companyName: v.companyName,
      ownerName: v.ownerName,
      address: v.address || '',
      mobile,
      alternateMobile: cleanMobile(v.alternateMobile) || '',
      email: v.email || '',
      accountHolderName: v.accountHolderName || '',
      bankName: v.bankName || '',
      accountNumber: v.accountNumber || '',
      ifscCode: v.ifscCode || '',
      branchName: v.branchName || '',
      gstNumber: v.gstNumber || '',
      panNumber: v.panNumber || '',
      workTypes,
      ...(ref1 && { reference1: ref1 }),
      ...(ref2 && { reference2: ref2 }),
      ...(averageTurnover !== undefined && { averageTurnover }),
    };

    const existing = await Contractor.findOne({ vendorCode: v.vendorCode });
    if (existing) {
      await Contractor.updateOne({ vendorCode: v.vendorCode }, { $set: payload });
      console.log(`UPDATED  ${v.vendorCode} → ${v.companyName}`);
      updated++;
    } else {
      await Contractor.create({ vendorCode: v.vendorCode, ...payload });
      console.log(`CREATED  ${v.vendorCode} → ${v.companyName}`);
      created++;
    }
  }

  console.log(`\nDone — Updated: ${updated} | Created: ${created}`);
  await mongoose.disconnect();
}

run().catch(err => { console.error(err); process.exit(1); });
