const AdvanceSlip   = require('../models/AdvanceSlip');
const Contractor    = require('../models/Contractor');
const asyncHandler  = require('../utils/asyncHandler');
const { success, notFound, badRequest } = require('../utils/responseFormatter');
const { nextCode } = require('../utils/sequence');
const { logAudit } = require('../utils/auditLog');
const { notifyByPermission } = require('../utils/notificationService');

const nextSlipNo = () => nextCode('advanceSlipNo', 'ADV-', 4);

// contractorName is snapshotted onto the AdvanceSlip at creation time and
// never re-synced if the Contractor master record is later corrected (same
// class of bug as WorkOrder's vendorName/ownerName/mobile — see
// workOrderController.js's overlayLiveContractorFields). This overlays the
// live companyName for display without touching what's actually stored on
// the slip, falling back to the stored snapshot when no live Contractor is
// found (e.g. it was deleted).
async function overlayLiveContractorNames(slips) {
  const codes = [...new Set(slips.filter(s => s.contractorCode).map(s => s.contractorCode))];
  if (!codes.length) return slips;
  const contractors = await Contractor.find({ vendorCode: { $in: codes } }).select('vendorCode companyName').lean();
  const nameByCode = new Map(contractors.map(c => [c.vendorCode, c.companyName]));
  slips.forEach((slip) => {
    const liveName = nameByCode.get(slip.contractorCode);
    if (liveName) slip.contractorName = liveName;
  });
  return slips;
}

// AdvanceSlip's `balance` (amount - amountRecovered) is a Mongoose virtual
// (see models/AdvanceSlip.js) — it's never materialized by `.lean()`, which
// both listAdvanceSlips and getPendingAdvances use (so the live-Contractor-
// name overlay above can mutate plain objects). Compute it manually here,
// using the exact same formula as the virtual, on every plain object.
function attachBalance(slips) {
  slips.forEach((slip) => {
    slip.balance = slip.amount - slip.amountRecovered;
  });
  return slips;
}

// GET /api/advance-slips
exports.listAdvanceSlips = asyncHandler(async (req, res) => {
  const filter = {};
  if (req.query.projectId)      filter.projectId      = req.query.projectId;
  if (req.query.contractorCode) filter.contractorCode = req.query.contractorCode;
  if (req.query.status)         filter.status         = req.query.status;
  if (req.query.archived === 'true') filter.isArchived = true;
  else                                filter.isArchived = { $ne: true };

  // populate('createdBy') so the redesigned detail modal/print can show a
  // real "Generated By" name (mirrors RunningBill's own populated
  // requestedBy/verificationBy/etc. — see billController.js::listBills).
  const slips = await AdvanceSlip.find(filter).populate('createdBy', 'name').sort({ createdAt: -1 }).lean();
  await overlayLiveContractorNames(slips);
  attachBalance(slips);
  success(res, { advanceSlips: slips });
});

// GET /api/advance-slips/pending?projectId=X&vendorCode=Y
// Returns outstanding/partial advances for a contractor+project (used at Release Payment)
exports.getPendingAdvances = asyncHandler(async (req, res) => {
  const { projectId, vendorCode } = req.query;
  if (!projectId || !vendorCode) return badRequest(res, 'projectId and vendorCode are required');

  const slips = await AdvanceSlip.find({
    projectId,
    contractorCode: vendorCode,
    status: { $in: ['outstanding', 'partial'] },
    isArchived: { $ne: true },
  }).sort({ date: 1 }).lean();
  await overlayLiveContractorNames(slips);
  attachBalance(slips);

  success(res, { advanceSlips: slips });
});

// POST /api/advance-slips
exports.createAdvanceSlip = asyncHandler(async (req, res) => {
  const { contractorCode, contractorName, projectId, projectName, amount, date, reference, notes } = req.body;
  if (!contractorCode || !projectId || amount === undefined || amount === null || !date) {
    return badRequest(res, 'contractorCode, projectId, amount and date are required');
  }

  const numAmount = Number(amount);
  if (typeof amount === 'boolean' || isNaN(numAmount) || !isFinite(numAmount) || numAmount <= 0) {
    return badRequest(res, 'Advance amount must be a valid number greater than 0');
  }

  const slipNo = await nextSlipNo();
  const slip = await AdvanceSlip.create({
    slipNo, contractorCode, contractorName, projectId, projectName,
    amount: numAmount, date, reference, notes, createdBy: req.user._id,
  });

  await logAudit({
    action: 'CREATE', module: 'advance-slips', user: req.user,
    description: `Advance slip ${slipNo} created for ${contractorName || contractorCode} (₹${numAmount.toLocaleString('en-IN')})`,
    entityType: 'AdvanceSlip', entityId: slip._id, entityLabel: slip.slipNo,
  });

  notifyByPermission({
    module: 'advance-payments', action: 'view', roles: ['owner'], entityDoc: slip,
    type: 'ADVANCE_SLIP_CREATED', category: 'advance-recovery',
    title: `Advance Slip ${slipNo} created`,
    message: `₹${numAmount.toLocaleString('en-IN')} advance recorded for ${contractorName || contractorCode} on ${projectName || projectId}.`,
    entityType: 'AdvanceSlip', entityId: slip._id, link: `/advance-payments?open=${slip._id}`,
    excludeUserId: req.user._id,
  }).catch((err) => console.error('[notifications] ADVANCE_SLIP_CREATED notify failed', err.message));

  success(res, { advanceSlip: slip }, `Advance slip ${slipNo} created`);
});

// DELETE /api/advance-slips/:id  (owner only, only if no recoveries yet)
exports.deleteAdvanceSlip = asyncHandler(async (req, res) => {
  const slip = await AdvanceSlip.findById(req.params.id);
  if (!slip) return notFound(res, 'Advance slip not found');
  if (slip.amountRecovered > 0) return badRequest(res, 'Cannot delete a slip with recorded recoveries');
  await slip.deleteOne();

  await logAudit({
    action: 'DELETE', module: 'advance-slips', user: req.user,
    description: `Advance slip ${slip.slipNo} deleted`,
    entityType: 'AdvanceSlip', entityId: slip._id, entityLabel: slip.slipNo,
  });

  success(res, {}, 'Advance slip deleted');
});

// ── Archive / Unarchive ────────────────────────────────────────
exports.archiveAdvanceSlip = asyncHandler(async (req, res) => {
  const slip = await AdvanceSlip.findById(req.params.id);
  if (!slip) return notFound(res, 'Advance slip not found');
  slip.isArchived = true;
  slip.archivedAt = new Date();
  await slip.save();

  await logAudit({
    action: 'UPDATE', module: 'advance-slips', user: req.user,
    description: `Advance slip ${slip.slipNo} archived`,
    entityType: 'AdvanceSlip', entityId: slip._id, entityLabel: slip.slipNo,
  });

  success(res, { advanceSlip: slip }, 'Advance slip archived');
});

exports.unarchiveAdvanceSlip = asyncHandler(async (req, res) => {
  const slip = await AdvanceSlip.findById(req.params.id);
  if (!slip) return notFound(res, 'Advance slip not found');
  slip.isArchived = false;
  slip.archivedAt = null;
  await slip.save();

  await logAudit({
    action: 'UPDATE', module: 'advance-slips', user: req.user,
    description: `Advance slip ${slip.slipNo} unarchived`,
    entityType: 'AdvanceSlip', entityId: slip._id, entityLabel: slip.slipNo,
  });

  success(res, { advanceSlip: slip }, 'Advance slip unarchived');
});

// PATCH /api/advance-slips/archive-bulk  — body: { ids: string[] }
exports.archiveAdvanceSlipsBulk = asyncHandler(async (req, res) => {
  const { ids } = req.body;
  if (!Array.isArray(ids) || ids.length === 0) return badRequest(res, 'Provide at least one advance slip id');
  await AdvanceSlip.updateMany({ _id: { $in: ids } }, { isArchived: true, archivedAt: new Date() });
  success(res, {}, `${ids.length} advance slip(s) archived`);
});

// PATCH /api/advance-slips/unarchive-bulk  — body: { ids: string[] }
exports.unarchiveAdvanceSlipsBulk = asyncHandler(async (req, res) => {
  const { ids } = req.body;
  if (!Array.isArray(ids) || ids.length === 0) return badRequest(res, 'Provide at least one advance slip id');
  await AdvanceSlip.updateMany({ _id: { $in: ids } }, { isArchived: false, archivedAt: null });
  success(res, {}, `${ids.length} advance slip(s) unarchived`);
});
