const router     = require('express').Router();
const { authenticate, authorizeOr } = require('../middleware/auth');
const {
  listBillRequests,
  createBillRequest,
  createBatchBillRequest,
  approveBillRequest,
  rejectBillRequest,
  markMilestone,
  archiveBillRequest,
  unarchiveBillRequest,
  archiveBillRequestsBulk,
  unarchiveBillRequestsBulk,
} = require('../controllers/billRequestController');

router.use(authenticate);

router.get('/',                listBillRequests);
// Bill requests are now generated by AGM/GM reviewing DRI progress (not by
// DRI themselves) — Owner keeps a direct bypass. authorizeOr so an explicit
// permission grant works too, not just the hardcoded role list.
router.post('/batch',          authorizeOr('bill-requests', 'create', 'owner', 'gm', 'agm'), createBatchBillRequest);
router.post('/',               authorizeOr('bill-requests', 'create', 'owner', 'gm', 'agm'), createBillRequest);
// Stage 1 (AGM sets hold/advance and approves) — restricted to AGM/owner only.
router.put('/:id/approve',   authorizeOr('bill-requests', 'approve', 'owner', 'agm'), approveBillRequest);
router.put('/:id/reject',    authorizeOr('bill-requests', 'approve', 'owner', 'agm', 'gm', 'accounts'), rejectBillRequest);
// Stage 5 (Accounts releases payment, only once the linked bill is 'payment-initiated').
router.put('/:id/milestone', authorizeOr('bill-requests', 'approve', 'owner', 'accounts'), markMilestone);
router.patch('/archive-bulk',   authorizeOr('bill-requests', 'edit', 'owner', 'gm', 'accounts'), archiveBillRequestsBulk);
router.patch('/unarchive-bulk', authorizeOr('bill-requests', 'edit', 'owner', 'gm', 'accounts'), unarchiveBillRequestsBulk);
router.patch('/:id/archive',    authorizeOr('bill-requests', 'edit', 'owner', 'gm', 'accounts'), archiveBillRequest);
router.patch('/:id/unarchive',  authorizeOr('bill-requests', 'edit', 'owner', 'gm', 'accounts'), unarchiveBillRequest);

module.exports = router;
