const router     = require('express').Router();
const { authenticate, authorizeOr, authorizeAnyOr } = require('../middleware/auth');
const {
  listBillRequests,
  createBillRequest,
  createBatchBillRequest,
  agmApprove,
  gmApprove,
  l3Approve,
  l4Approve,
  rejectBillRequest,
  archiveBillRequest,
  unarchiveBillRequest,
  archiveBillRequestsBulk,
  unarchiveBillRequestsBulk,
} = require('../controllers/billRequestController');

router.use(authenticate);

router.get('/',                listBillRequests);
// Bill requests are now generated by AGM/GM reviewing DRI progress (not by
// DRI themselves) — Owner keeps a direct bypass. authorizeOr so an explicit
// permission grant works too, not just the hardcoded role list.
router.post('/batch',          authorizeOr('bill-requests', 'create'), createBatchBillRequest);
router.post('/',               authorizeOr('bill-requests', 'create'), createBillRequest);
// Stage 1 (AGM sets hold/advance, forwards to GM) — AGM/owner only.
router.put('/:id/agm-approve', authorizeOr('bill-requests', 'agm-approve'), agmApprove);
// Stage 2 (GM signs off) — finalizes the bill for the default 2-level
// department, or moves on to L3 for a department configured for 3/4.
router.put('/:id/gm-approve',  authorizeOr('bill-requests', 'gm-approve'), gmApprove);
// Stages 3/4 — only ever reachable when a department's Approval Rule (Users
// → Departments) is configured for 3/4 levels; no hardcoded role bypass
// beyond owner, since no role in this org is inherently "the L3/L4 approver"
// (approverAllowed's per-department config is what actually decides who
// qualifies once the request is genuinely at that stage).
router.put('/:id/l3-approve',  authorizeOr('bill-requests', 'l3-approve'), l3Approve);
router.put('/:id/l4-approve',  authorizeOr('bill-requests', 'l4-approve'), l4Approve);
// Reject's target status depends on which stage it's at —
// authorizeAnyOr since any stage's action-holder can reject at their stage.
router.put('/:id/reject',    authorizeAnyOr('bill-requests', ['agm-approve', 'gm-approve', 'l3-approve', 'l4-approve']), rejectBillRequest);
// Payment release lives entirely in the Accounts Payment module now (see
// billController.releasePayment) — no milestone route here anymore.
router.patch('/archive-bulk',   authorizeOr('bill-requests', 'edit'), archiveBillRequestsBulk);
router.patch('/unarchive-bulk', authorizeOr('bill-requests', 'edit'), unarchiveBillRequestsBulk);
router.patch('/:id/archive',    authorizeOr('bill-requests', 'edit'), archiveBillRequest);
router.patch('/:id/unarchive',  authorizeOr('bill-requests', 'edit'), unarchiveBillRequest);

module.exports = router;
